apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-config-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-demo
  template:
    metadata:
      labels:
        app: mariadb-demo
    spec:
      containers:
        - name: mariadb
          image: mariadb
          envFrom:
            - configMapRef:
                name: db-config
